### ISSUE TITLE
Property not rendered correctly in Neos 8.3 with PHP 8.2

### ISSUE THREAD

**Issue by markwatney2016** [Sebobo/Shel.Neos.ColorPicker#77]
Does this package work with Neos 8.3 and PHP 8.2?

```
"php": "~8.2.0",
"neos/neos": "~8.3.0",
"neos/neos-ui": "~8.3.0",
"shel/neos-colorpicker": "^1.6.4"
```

This is my property configuration:

```
    foo:
      type: string
      ui:
        label: 'Lorem ipsum'
        reloadIfChanged: true
        inspector:
          group: imagemenu
          editor: 'Shel.Neos.ColorPicker/ColorPickerEditor'
```

This is how it is rendered in the UI:

<img width="437" alt="grafik" src="https://user-images.githubusercontent.com/22563689/236919182-22a0e785-e5de-4067-8527-0d5fa68bf7a6.png">

...it's an text input field with dark background that prevents me even from typing a string in.
